"use client";

import { useEffect, useMemo, useState } from "react";
import { Address } from "viem";
import {
  useDeployedContractInfo,
  useScaffoldWriteContract,
} from "~~/hooks/scaffold-eth";

const ZERO: Address = "0x0000000000000000000000000000000000000000";

function isAddressLike(x: string): x is Address {
  return /^0x[a-fA-F0-9]{40}$/.test(x);
}

export default function PoolPage() {
  // Deployed contract infos from hardhat-deploy (auto-generated by SE-2 after yarn deploy)
  const { data: helperInfo } = useDeployedContractInfo("UniV3PoolHelper");
  const { data: marketInfo } = useDeployedContractInfo("PredictionMarketERC20");

  const helperAddress = (helperInfo?.address ?? "") as Address;
  const marketDeployedAddress = (marketInfo?.address ?? "") as Address;

  // Write handle for UniV3PoolHelper
  const { writeContractAsync, isPending } = useScaffoldWriteContract("UniV3PoolHelper");

  // Form state
  const [marketAddr, setMarketAddr] = useState<Address>(ZERO);
  const [betId, setBetId] = useState<string>("");

  // Prefill market if deployed locally/testnet
  useEffect(() => {
    if (marketDeployedAddress && isAddressLike(marketDeployedAddress)) {
      setMarketAddr(marketDeployedAddress);
    }
  }, [marketDeployedAddress]);

  const validMarket = useMemo(() => isAddressLike(marketAddr), [marketAddr]);
  const validBetId = useMemo(() => /^\d+$/.test(betId) && BigInt(betId) >= 0n, [betId]);

  const canSubmit =
    !!helperAddress &&
    validMarket &&
    validBetId &&
    marketAddr !== ZERO;

  const onEnsurePoolsForBet = async () => {
    // Calls: ensurePoolsForBet(address market, uint256 betId)
    await writeContractAsync({
      functionName: "ensurePoolsForBet",
      args: [marketAddr, BigInt(betId)],
    });
  };

  return (
    <main className="p-6 mx-auto w-full max-w-2xl space-y-6">
      <header className="space-y-1">
        <h1 className="text-2xl font-bold">Pool Helper</h1>
        <p className="text-sm opacity-80">
          Helper contract: <b>{helperAddress || "not deployed"}</b>
        </p>
      </header>

      <section className="card border rounded-2xl p-5 space-y-4">
        {!helperAddress && (
          <p className="text-warning text-sm">
            Deploy <code>UniV3PoolHelper</code> first (e.g.{" "}
            <code>packages/hardhat/deploy/02_deploy_pool.ts</code>) and reload the page.
          </p>
        )}

        <label className="text-sm w-full">
          PredictionMarketERC20 address
          <input
            className={`input input-bordered w-full mt-1 ${validMarket || marketAddr === ZERO ? "" : "input-error"}`}
            placeholder="0x…"
            value={marketAddr}
            onChange={e => setMarketAddr((e.target.value || "") as Address)}
          />
          {marketDeployedAddress && (
            <div className="text-xs opacity-70 mt-1">
              Detected deployed market: {marketDeployedAddress}
            </div>
          )}
        </label>

        <label className="text-sm w-full">
          Bet ID
          <input
            className={`input input-bordered w-full mt-1 ${validBetId || betId === "" ? "" : "input-error"}`}
            placeholder="e.g. 0"
            inputMode="numeric"
            value={betId}
            onChange={e => setBetId(e.target.value)}
          />
        </label>

        <div className="pt-2">
          <button
            className="btn btn-primary"
            disabled={!canSubmit || isPending}
            onClick={onEnsurePoolsForBet}
            title={
              !helperAddress
                ? "Helper not deployed?"
                : !canSubmit
                ? "Fill a valid market address and bet id"
                : "Create/ensure TAB–YES and TAB–NO pools"
            }
          >
            {isPending ? "Confirm in wallet…" : "Ensure Pools for Bet"}
          </button>
        </div>

        <p className="text-xs opacity-70 leading-relaxed">
          This page calls <code>ensurePoolsForBet(market, betId)</code>. The helper will:
          <br />• read <code>collateral()</code> and <code>getBetTokens(betId)</code> from your market
          <br />• create/init Uniswap V3 pools TAB–YES and TAB–NO at 1% fee, price 1:1 (if not already)
        </p>
      </section>
    </main>
  );
}
